language: python
python:
 - "3.2"
install:
 - echo | sudo add-apt-repository ppa:pyside
 - sudo apt-get update -qq
 - sudo apt-get install -qq python-pyside
 - sudo apt-get install -qq python3-pyside
script:
 - python test_sexton.py
